### ISSUE TITLE
Crash when trying to use the library on MacOS 11.5.2

### ISSUE THREAD

**Issue by csmaxx** [ICToolkit/SwiftyMonaco#6]
Hi I've tried to use the library. but the app just crashes with the following message

`2021-08-30 20:32:59.666406+0200 DBTools[58086:3348586] [Process] 0x7f9ced032020 - [pageProxyID=5, webPageID=6, PID=0] WebPageProxy::tryReloadAfterProcessTermination: process crashed and the client did not handle it, not reloading the page because we reached the maximum number of attempts`

Steps to reproduce:

1. Created a new project in Xcode (MacOS app - SwiftUI lifecycle)
2. added the package dependency (File -> Swift Packages -> Add Package Dependency...)
3. Pasted in the Repo URL
4. Added the SwiftyMonaco to the view as per. your example.

When I run the app nothing happens.
I've tried both the Static and Dynamicly linked.

**Comment by pkasila** [comment]
@csmaxx Yeah, there is a problem with that. It happens because Monaco Editor runs inside `WKWebView` and macOS considers it as an outgoing connection which should be allowed in App Sandbox (`Network -> Outgoing connections (Client)`):

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/17158860/131391125-996cf6de-228b-41f4-b240-722437a62f64.png">

Yeah, it's a little bit confusing, so I'll add it to the `README.md` and Wiki section later. If the issue has or has not been solved, let me know.

**Comment by csmaxx** [comment]
@pkasila It works now after enabling the Network option :-)
